# render.yaml — Infrastructure as Code para o Render
# Referência: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: biblioteca-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    healthCheckPath: /actuator/health

    envVars:
      - key: DB_URL
        value: jdbc:postgresql://dpg-d8kvr9ugvqtc73ad8l9g-a:5432/biblioteca_5ihl
      - key: DB_USERNAME
        value: biblioteca
      - key: DB_PASSWORD
        sync: false          # definir no dashboard (segredo)
      - key: JWT_SECRET
        sync: false          # definir no dashboard (segredo)
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: MAIL_USERNAME
        sync: false          # definir no dashboard
      - key: MAIL_PASSWORD
        sync: false          # definir no dashboard (segredo)
      - key: EMAIL_DESTINATARIOS
        sync: false          # definir no dashboard
      - key: PORT
        value: "8080"
