# Perfil local (docker compose ou IDE)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/biblioteca}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}
jwt.secret=${JWT_SECRET:YVqblLlH085go6E7HywZH562IqqMjV_gAvpdLnDtuks=}
