spring.application.name=biblioteca

spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

server.port=${PORT:8080}
server.error.include-message=always
server.error.include-binding-errors=always
spring.output.ansi.enabled=ALWAYS

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method

biblioteca.openapi.dev-url=http://localhost:8080
biblioteca.openapi.prod-url=https://api.biblioteca.com.br

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.locale=pt_BR

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.file.name=logs/biblioteca.log

# ================================
# JWT

jwt.secret=01010010_01100001_01111001_01101100_01100001
jwt.expiration=86400000

# Email (SMTP - Gmail)
# ================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=false

biblioteca.email.destinatario = marcelo.collares@docente.firjan.senai.br,matheus.santos@residente.serratec.org,caique.araujo@residente.serratec.org,rayla.ferreira@residente.serratec.org,patrick.lima@residente.serratec.org,simone.bromerschenckel@residente.serratec.org